from pathlib import Path
from typing import Protocol

from legacyflow.models.contracts import Action, Condition, Observation, Target


class ComputerSurface(Protocol):
    owner: str
    session_id: str

    async def observe(self) -> Observation: ...
    async def execute(self, action: Action, inputs: dict[str, str]) -> None: ...
    async def verify(self, condition: Condition, inputs: dict[str, str]) -> None: ...
    async def read(self, target: Target) -> str: ...
    async def screenshot(self, path: Path) -> None: ...
